# minilab: Ασκήσεις εξάσκησης - Αριθμητική Python και Προεπεξεργασία δεδομένων

## Η βιβλιοθήκη ``NumPy``

### Exercise 1: Creating and Manipulating NumPy Arrays

Create an array of 10 zeros.

In [ ]:
# Implement code here

Create an array of 10 ones.

In [ ]:
# Implement code here

Create an array of 10 fives.

In [ ]:
# Implement code here

Create an array of the integers from 10 to 50.

In [ ]:
# Implement code here

Create an array of all the even integers from 10 to 50:

1. Using the NumPy's method ``arange()``.

2. Using the NumPy's method ``array()`` and a list comprehension with a conditional.

In [ ]:
# Implement code here

Create a 3x3 identity matrix.

In [ ]:
# Implement code here

Create an array of 20 linearly spaced points between 0 and 1.

In [ ]:
# Implement code here

Create a NumPy array containing the integers from 1 to 10. Then, write code to:

1. Print the shape and dimensions of the array.

2. Calculate the sum of all the elements in the array.

3. Calculate the mean of the array.

In [ ]:
# Implement code here

Use NumPy to generate a random number between 0 and 1.

In [ ]:
# Implement code here

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [ ]:
# Implement code here

### Exercise 2: Indexing and Slicing

Create a 2D NumPy array of shape (3, 4) with random integers. Write code to:

1. Print the element at the second row and third column.

2. Extract the first two rows and the last two columns of the array.

3. Calculate the sum of all the elements in the second column.

In [ ]:
# Implement code here

Write code to create the following matrix. This starting matrix will be used subsequently to perform slicing operations.

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [ ]:
# Implement code here

Write code that reproduces the output shown below:

```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [ ]:
# Implement code here

Write code that retrieves the number 20 from the matrix.

In [ ]:
# Implement code here

Write code that reproduces the output shown below:

```python
array([[ 2],
       [ 7],
       [12]])
```

In [ ]:
# Implement code here

Write code that reproduces the output shown below:

```python
array([21, 22, 23, 24, 25])
```

In [ ]:
# Implement code here

Write code that reproduces the output shown below:

```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [ ]:
# Implement code here

### Exercise 3: Element-wise Operations

Create the following matrix using element-wise operations:

```python
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

In [ ]:
# Implement code here

Create two 1D NumPy arrays of the same length with random numbers. Write code to:

1. Add the two arrays element-wise and store the result in a new array.

2. Multiply one of the arrays by a scalar value.

3. Find the maximum value in the resulting array.

In [ ]:
# Implement code here

### Exercise 4: Reshaping and Transposing

Create a 3x3 matrix with values ranging from 0 to 8.

In [ ]:
# Implement code here

Create a 2D NumPy array of shape (3, 5) with random integers. Write code to:

1. Reshape the array into a (5, 3) shape.

2. Transpose the reshaped array.

In [ ]:
# Implement code here

### Exercise 5: Array Concatenation

Create two 1D NumPy arrays of the same length. Write code to:

1. Concatenate the arrays horizontally.

2. Concatenate the arrays vertically.

In [ ]:
# Implement code here

### Exercise 6: Boolean Indexing

Create a 1D NumPy array of random integers. Write code to:

1. Find and print all elements greater than a specific value (e.g., 5).

2. Calculate the mean of the elements greater than the specific value.

In [ ]:
# Implement code here

### Exercise 7: Array Comparison and Filtering

Create a 1D NumPy array of random integers. Write code to:

1. Find and print the indices of elements that are greater than a specific value (e.g., 7).

2. Create a new array containing only the elements greater than the specific value.

In [ ]:
# Implement code here

### Exercise 8: Element-wise Multiplication

Create two 2D NumPy arrays of the same shape. Write code to multiply the two arrays element-wise.

In [ ]:
# Implement code here

### Exercise 9: Computing Statistics

Create a 1D NumPy array of random floats. Write code to:

1. Find and print the minimum and maximum values in the array.

2. Calculate the standard deviation of the array.

3. Calculate the sum of all the columns in the array.

In [ ]:
# Implement code here

### Exercise 10: Element-wise Absolute Values

Create a 2D NumPy array with both positive and negative integers. Write code to calculate the absolute values of all elements in the array.

In [ ]:
# Implement code here

### Exercise 11: Reading Data from File 

Read in the file called ``nearest_stars.txt`` in the data directory and determine the standard deviation of the distances of the stars with spectral type M.

In [ ]:
# Implement code here

### Exercise 12.1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of x- and y-data as follows:

1. Assign a sequence of numbers from 6 to 20 (inclusive) to a ``NumPy`` array named ``x_data``.


2. Assign 15 values to a ``NumPy`` array named ``y_data`` such that: $$y = 3x + 4$$

In [ ]:
# Implement code here

### Exercise 12.2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the ``y_data`` array you already created. To be more precise, modify each value assigned to ``y_data`` by adding a different random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a noise array, called ``noise``, having the same dimension as ``y_data``.

> **Hint**: Use the method [np.random.random_sample](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random_sample.html#numpy.random.random_sample)

In [ ]:
# Implement code here