# minilab: Ασκήσεις εξάσκησης - Αριθμητική Python και Προεπεξεργασία δεδομένων

## Η βιβλιοθήκη ``NumPy``

In [1]:
# Import the numpy module here once
import numpy as np

### Exercise 1: Creating and Manipulating NumPy Arrays

Create a NumPy array containing the integers from 1 to 10. Then, write code to:

1. Print the shape and dimensions of the array.

2. Calculate the sum of all the elements in the array.

3. Calculate the mean of the array.

In [2]:
# Create the array
arr = np.arange(1, 11)

# 1. Print shape and dimensions
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)

# 2. Calculate sum
sum_elements = np.sum(arr)
print("Sum:", sum_elements)

# 3. Calculate mean
mean_value = np.mean(arr)
print("Mean:", mean_value)

Shape: (10,)
Dimensions: 1
Sum: 55
Mean: 5.5


### Exercise 2: Indexing and Slicing

Create a 2D NumPy array of shape (3, 4) with random integers. Write code to:

1. Print the element at the second row and third column.

2. Extract the first two rows and the last two columns of the array.

3. Calculate the sum of all the elements in the second column.

In [3]:
# Create a 2D array
arr_2d = np.random.randint(1, 10, size=(3, 4))

# 1. Print element at second row and third column
print("Element at 2nd row, 3rd col:", arr_2d[1, 2])

# 2. Extract first two rows and last two columns
subset = arr_2d[:2, -2:]
print("Subset:\n", subset)

# 3. Calculate sum of the second column
sum_second_column = np.sum(arr_2d[:, 1])
print("Sum of the second column:", sum_second_column)

Element at 2nd row, 3rd col: 3
Subset:
 [[3 3]
 [3 3]]
Sum of the second column: 13


### Exercise 3: Element-wise Operations

Create two 1D NumPy arrays of the same length with random numbers. Write code to:

1. Add the two arrays element-wise and store the result in a new array.

2. Multiply one of the arrays by a scalar value.

3. Find the maximum value in the resulting array.

In [4]:
# Create two 1D arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# 1. Add arrays element-wise
result_add = arr1 + arr2
print("Element-wise addition:", result_add)

# 2. Multiply one array by a scalar
scalar = 2
result_multiply = arr1 * scalar
print("Multiplication by a scalar:", result_multiply)

# 3. Find maximum value in the result
max_value = np.max(result_add)
print("Maximum value:", max_value)

Element-wise addition: [6 6 6 6 6]
Multiplication by a scalar: [ 2  4  6  8 10]
Maximum value: 6


### Exercise 4: Reshaping and Transposing

Create a 2D NumPy array of shape (3, 5) with random integers. Write code to:

1. Reshape the array into a (5, 3) shape.

2. Transpose the reshaped array.

In [5]:
# Create a 2D array
arr_2d = np.random.randint(1, 10, size=(3, 5))

# 1. Reshape into (5, 3)
reshaped_arr = arr_2d.reshape((5, 3))
print("Reshaped array:\n", reshaped_arr)

# 2. Transpose the reshaped array
transposed_arr = reshaped_arr.T
print("Transposed array:\n", transposed_arr)

Reshaped array:
 [[2 9 1]
 [5 1 4]
 [4 3 7]
 [2 5 8]
 [1 5 6]]
Transposed array:
 [[2 5 4 2 1]
 [9 1 3 5 5]
 [1 4 7 8 6]]


### Exercise 5: Array Concatenation

Create two 1D NumPy arrays of the same length. Write code to:

1. Concatenate the arrays horizontally.

2. Concatenate the arrays vertically.

In [6]:
# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 1. Concatenate horizontally
horizontal_concat = np.concatenate((arr1, arr2))
print("Horizontal Concatenation:", horizontal_concat)

# 2. Concatenate vertically
vertical_concat = np.vstack((arr1, arr2))
print("Vertical Concatenation:\n", vertical_concat)

Horizontal Concatenation: [1 2 3 4 5 6]
Vertical Concatenation:
 [[1 2 3]
 [4 5 6]]


### Exercise 6: Boolean Indexing

Create a 1D NumPy array of random integers. Write code to:

1. Find and print all elements greater than a specific value (e.g., 5).

2. Calculate the mean of the elements greater than the specific value.

In [7]:
# Create a 1D array
arr = np.random.randint(1, 10, size=10)

# 1. Find elements greater than 5
greater_than_5 = arr[arr > 5]
print("Elements greater than 5:", greater_than_5)

# 2. Calculate mean of elements greater than 5
mean_greater_than_5 = np.mean(greater_than_5)
print("Mean of elements greater than 5:", mean_greater_than_5)

Elements greater than 5: [9 8 8 8]
Mean of elements greater than 5: 8.25


### Exercise 7: Array Comparison and Filtering

Create a 1D NumPy array of random integers. Write code to:

1. Find and print the indices of elements that are greater than a specific value (e.g., 7).

2. Create a new array containing only the elements greater than the specific value.

In [8]:
# Create a 1D array
arr = np.random.randint(1, 10, size=10)

# 1. Find indices of elements greater than 7
indices_greater_than_7 = np.where(arr > 7)
print("Indices of elements greater than 7:", indices_greater_than_7)

# 2. Create a new array with elements greater than 7
new_arr = arr[arr > 7]
print("New array with elements greater than 7:", new_arr)

Indices of elements greater than 7: (array([3]),)
New array with elements greater than 7: [9]


### Exercise 8: Element-wise Multiplication

Create two 2D NumPy arrays of the same shape. Write code to multiply the two arrays element-wise.

In [9]:
# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 3], [4, 5]])

# Multiply arrays element-wise
result = arr1 * arr2
print("Element-wise multiplication result:\n", result)

Element-wise multiplication result:
 [[ 2  6]
 [12 20]]


### Exercise 9: Computing Statistics

Create a 1D NumPy array of random floats. Write code to:

1. Find and print the minimum and maximum values in the array.

2. Calculate the standard deviation of the array.

In [10]:
# Create a 1D array of random floats
arr = np.random.rand(10)

# 1. Find minimum and maximum values
min_value = np.min(arr)
max_value = np.max(arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 2. Calculate standard deviation
std_deviation = np.std(arr)
print("Standard Deviation:", std_deviation)

Minimum value: 0.10602002333109872
Maximum value: 0.9164314854464037
Standard Deviation: 0.2998350516297167


### Exercise 10: Element-wise Absolute Values

Create a 2D NumPy array with both positive and negative integers. Write code to calculate the absolute values of all elements in the array.

In [11]:
# Create a 2D array with positive and negative integers
arr = np.array([[1, -2, 3], [-4, 5, -6]])

# Calculate absolute values
abs_values = np.abs(arr)
print("Absolute values:\n", abs_values)

Absolute values:
 [[1 2 3]
 [4 5 6]]


### Exercise 11: Reading Data from File 

Read in the file called ``nearest_stars.txt`` in the data directory and determine the standard deviation of the distances of the stars with spectral type M.

In [12]:
# Use genfromtxt to read the data

# Explanation of parameters:
# - 'delimiter' : Specifies the character that separates the columns (in this case, a comma).
# - 'dtype=None': Automatically determines the data type of each column.
# - 'names=True': Treats the first row as column names (header).
data = np.genfromtxt("../data/nearest_stars.txt", delimiter=',', dtype=None, names=True, encoding=None)

# Now you can access the data using column names as keys

# Filter the data to select rows with spectral type "M"
m_type_stars = data[data['Spectral_Type'] == 'M']

# Extract the distances for "M" type stars
distances_m_type = m_type_stars['Distance']

# Calculate the standard deviation
std_deviation = np.std(distances_m_type)

print("Standard Deviation of Distances for Spectral Type 'M' Stars:", std_deviation)

Standard Deviation of Distances for Spectral Type 'M' Stars: 1.5982680475674285
