# Αριθμητική Python

## Η βιβλιοθήκη NumPy

Η βιβλοθήκη ``NumPy`` αποτελεί το κύριο πακέτο αριθμητικών μεθόδων και μαθηματικών υπολογισμών με την Python. Μπορεί να επεξεργαστεί πίνακες Ν-διαστάσεων, σύνθετους μετασχηματισμούς πινάκων, γραμμική άλγεβρα, μετασχηματισμούς Fourier και πολλά ακόμη.


Η βασική δομή/κλάση αντικειμένων της numpy είναι η ``ndarray`` η οποία δίνει τη δυνατότητα να ορισθούν διανύσματα και πίνακες Ν-διαστάσεων, ενώ ταυτόχρονα παρέχει προχωρημένες δυνατότητες χειρισμού των τελευταίων.


Η δομή ``ndarray`` είναι μία κλάση που μοιάζει πολύ με τη δομή ``list`` της Python. Σε αντίθεση, όμως, με τις λίστες η διάσταση ενός array είναι ορισμένη από την αρχή και αποθηκεύει αντικείμενα που είναι **μόνο του ίδιου τύπου** (δηλ. ``int``, ``float``, ``boolean``, ``str`` κτλ).


Ένας πίνακας array της ``NumPy`` είναι μία **πολυδιάστατη**, **ομοιόμορφη** και **διατεταγμένη** ακολουθία **συγκεκριμένου τύπου** δεδομένων που δεικτοδοτούνται μέσω θετικών ακεραίων.


Υπάρχουν διάφορες εντολές οι οποίες μας δίνουν πληροφορίες για ένα αντικείμενο ``ndarray``. Οι βασικότερες ιδιότητες ενός τέτοιου αντικειμένου είναι :

1. ``ndim``: ο αριθμός των διαστάσεων του πίνακα. Ο αριθμός αυτός αναφέρεται στην Python ως rank.

2. ``shape``: Μια πλειάδα που καθορίζει το μέγεθος του πίνακα ως προς κάθε διάσταση. Πίνακας nxm έχει ως shape την τιμή (m,n).

3. ``dtype``: Ο τύπος των στοιχείων του πίνακα. Εκτός των βασικών τύπων της Python η βιβιοθήκη ``NumPy`` παρέχει επιπλέον τύπους όπως τα ``numpy.int32`` και ``numpy.float64``.

### Δημιουργία πινάκων & τύποι δεδομένων

* Ο πιο βασικός τρόπος δημιουργίας ενός πίνακα NumPy είναι με τη χρήση της μεθόδου ``numpy.array(seq)`` η οποία μετατρέπει μία ακολουθία (λίστα ή πλειάδα) σε ένα μονοδιάστατο αντικείμενο τύπου ``ndarray``.


* Στο παρακάτω παράδειγμα φαίνεται η εφαρμόγη της εν λόγω μεθόδου. Το αντικείμενο που προκύπτει είναι ουσιαστικά ένας μονοδιάστατος πίνακας - δηλαδή το **διάνυσμα** με συντεταγμένες [1,2,3].

In [1]:
import numpy as np

example_array = np.array([1,2,3])

print(type(example_array))
print(example_array.ndim)
print(example_array.shape)
print(example_array.dtype)

print(example_array)

<class 'numpy.ndarray'>
1
(3,)
int64
[1 2 3]


* Ο τύπος των δεδομένων καθορίζεται αυτόματα κατά τη δημιουργία ενός πίνακα, αλλά συνήθως οι συναρτήσεις της NumPy περιλαμβάνουν επίσης ένα προαιρετικό όρισμα για να καθοριστεί ρητά ο τύπο δεδομένων (dtype).


* Μπορούμε να αξιοποιήσουμε την ίδια μέθοδο ώστε να δημιουργήσουμε και πολυδιάστατους πίνακες χρησιμοποιώντας εμφωλευμένες λίστες.


* Στο παρακάτω παράδειγμα παρουσιάζεται η δημιουργία ενός 2D πίνακα.

In [2]:
# Create a 2D array of data type float64
two_dim_array = np.array([[1, 2], [2, 3]], dtype=np.float64)

print(type(two_dim_array))
print(two_dim_array.ndim)
print(two_dim_array.shape)
print(two_dim_array.dtype)

print(two_dim_array)

<class 'numpy.ndarray'>
2
(2, 2)
float64
[[1. 2.]
 [2. 3.]]


Η μέθοδος ``numpy.array(seq)`` βασίζεται, όπως είδαμε, στην μετατροπή μίας υπάρχουσας ακολουθίας της Python σε έναν πίνακα.

Εκτός αυτής της μεθόδου, υπάρχουν δεκάδες ακόμα συναρτήσεις της ``NumPy`` με τις οποίες μπορεί κανείς να δημιουργήσει έναν πίνακα. Παρακάτω θα παρουσιάσουμε συνοπτικά τους πιο συνηθισμένους. Αναζητείστε την τεκμηρίωση των μεθόδων αυτών για περισσότερες λεπτομέρειες.

#### Μέθοδοι για την δημιουργία 1D πινάκων

* Η μέθοδος ``numpy.arange(start, stop, pace)``: Δημιουργεί πίνακες με συνεχώς αυξανόμενες τιμές.

*Σημείωση*: Σε αντίθεση όμως με την ``range`` της Python, με τη μέθοδο ``arange`` της Numpy μπορούμε να χρησιμοποιήσουμε και πραγματικούς αριθμούς (όχι μόνο ακέραιους).

In [3]:
# Create an array from 0.2 to 10.2 (exclusive)
arr = np.arange(0.2, 10.4)
print(arr)

# Recreate the same array specifying the data type
arr = np.arange(0, 10, dtype=float)
print(arr)

#Create array from 0 to 10 (exclusive) with a pace of 0.5
arr = np.arange(0, 10, 0.5)
print(arr)

[ 0.2  1.2  2.2  3.2  4.2  5.2  6.2  7.2  8.2  9.2 10.2]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


* H μέθοδος ``numpy.linspace(start, stop, num)``: Δημιουργεί πίνακες με καθορισμένο αριθμό στοιχείων και με **ίσες** αποστάσεις μεταξύ των καθορισμένων τιμών αρχής και τέλους.


* Παρόμοια είναι και η μέθοδος ``numpy.logspace(start, stop, num)`` με τη διαφορά ότι η απόσταση μεταξύ των τιμών μεταβάλλεται λογαριθμικά.

In [4]:
arr = np.linspace(0, 15)
print(arr)

arr = np.linspace(0, 15, num=20)
print(arr)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]
[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]


In [5]:
arr = np.logspace(0, 15)
print(arr)

arr = np.logspace(0, 15, num=20)
print(arr)

[1.00000000e+00 2.02358965e+00 4.09491506e+00 8.28642773e+00
 1.67683294e+01 3.39322177e+01 6.86648845e+01 1.38949549e+02
 2.81176870e+02 5.68986603e+02 1.15139540e+03 2.32995181e+03
 4.71486636e+03 9.54095476e+03 1.93069773e+04 3.90693994e+04
 7.90604321e+04 1.59985872e+05 3.23745754e+05 6.55128557e+05
 1.32571137e+06 2.68269580e+06 5.42867544e+06 1.09854114e+07
 2.22299648e+07 4.49843267e+07 9.10298178e+07 1.84206997e+08
 3.72759372e+08 7.54312006e+08 1.52641797e+09 3.08884360e+09
 6.25055193e+09 1.26485522e+10 2.55954792e+10 5.17947468e+10
 1.04811313e+11 2.12095089e+11 4.29193426e+11 8.68511374e+11
 1.75751062e+12 3.55648031e+12 7.19685673e+12 1.45634848e+13
 2.94705170e+13 5.96362332e+13 1.20679264e+14 2.44205309e+14
 4.94171336e+14 1.00000000e+15]
[1.00000000e+00 6.15848211e+00 3.79269019e+01 2.33572147e+02
 1.43844989e+03 8.85866790e+03 5.45559478e+04 3.35981829e+05
 2.06913808e+06 1.27427499e+07 7.84759970e+07 4.83293024e+08
 2.97635144e+09 1.83298071e+10 1.12883789e+11 6.95192

#### Μέθοδοι για την δημιουργία 2D πινάκων

Οι συναρτήσεις για την δημιουργία διδιάστατων πινάκων (π.χ. ``numpy.eye()``, ``numpy.diag()``) ορίζουν τις ιδιότητες ειδικών πινάκων που αντιπροσωπεύονται ως πίνακες 2D και είναι ιδιαίτερα χρήσιμες στην περίπτωση της γραμμικής άλγεβρας.


* Η μέθοδος ``numpy.eye(n, m)``: Ορίζει τον 2D ταυτοτικό πίνακα. Τα διαγώνια στοιχεία (i=j) είναι ίσα με τη μονάδα ενώ τα μη-διαγώνια ίσα με μηδεν.


* Η μέθοδος ``numpy.diag(array)``: Ορίζει έναν τετραγωνικό 2D πίνακα με δοθέντες τιμές κατά μήκος της διαγωνίου. Στην περίπτωση που δίνεται ως όρισμα ένας 2D πίνακας επιστρέφει έναν 1D πίνακα που περιέχει μόνο τα διαγώνια στοιχεία.

In [6]:
arr = np.eye(3, 3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
arr = np.diag([1, 2, 3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [8]:
# A 2D array
a = np.array([[1, 2], [3, 4]])

arr = np.diag(a)
arr

array([1, 4])

#### Γενικές μέθοδοι για την δημιουργία N-διάστατων πινάκων

Οι πιο γενικές μέθοδοι για την δημιουργία πινάκων βασίζονται στον ορισμό των πινάκων μέσω των επιθυμητών διαστάσεων. Με άλλα λόγια, οι συναρτήσεις αυτές μπορούν να δημιουργήσουν έναν πίνακα με οποιεσδήποτε διαστάσεις, αρκεί να καθορίσουμε τον αριθμό των διαστάσεων καθώς και το μήκος σε κάθε διάσταση μέσω μίας λίστας ή πλειάδας.


* Οι μέθοδοι ``numpy.zeros(shape)`` και ``numpy.ones(shape)``: Δημιουργούν έναν πίνακα καθορισμένου σχήματος που αποτελείται από μηδενικά ή μονάδες αντίστοιχα.


* Οι μέθοδοι ``numpy.zeros_like(array)`` και ``numpy.ones_like(array)``: Δημιουργούν έναν πίνακα που αποτελείται από μηδενικά ή μονάδες αντίστοιχα, με ίδιο σχήμα και διαστάσεις όπως ο πίνακας που δόθηκε ως όρισμα.


* Οι μέθοδοι ``numpy.empty(shape)`` και ``numpy.full(shape, fill_value)``: Η πρώτη μέθοδος δημιουργεί έναν πίνακα καθορισμένου σχήματος που αποτελείται από αυθαίρετες (μη-αρχικοποιημένες) τιμές. Η χρήση της πρέπει να γίνεται με προσοχή. Η δεύτερη μέθοδος δημιουργεί έναν πίνακα καθορισμένου σχήματος που αποτελείται από την τιμή που έχουμε καθορίσει.


* Οι μέθοδοι ``numpy.empty_like(array)`` και ``numpy.full_like(array)``: Επιτελούν την ίδια λειτουργία με τις μεθόδους παραπάνω αλλά το σχήμα πλέον καθορίζεται από έναν άλλον πίνακα που δίνεται ως όρισμα.

In [9]:
# Passing the shape of the array using a list
arr = np.zeros([2,3])
print(arr)

# Passing the shape of the array using a tuple
arr = np.ones((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
x = np.array([[1, 2], [3, 4]])

# Example: Create an array using the zeros_like method
arr = np.zeros_like(x)
print(arr)

# Example: Create an array using the ones_like method
arr = np.ones_like(x)
print(arr)

[[0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [11]:
# Example: Create an array using the empty method
arr = np.empty((2,2))
print(arr)

# Example: Create an array using the full method
arr = np.full((2,2), 8.5)
print(arr)

[[0. 0.]
 [0. 0.]]
[[8.5 8.5]
 [8.5 8.5]]


In [12]:
x = np.array([[1, 2], [3, 4]])

# Example: Create an array using the empty_like method
arr = np.empty_like(x, dtype=float)
print(arr)

# Example: Create an array using the full_like method
arr = np.full_like(x, 8.5, dtype=float)
print(arr)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[[8.5 8.5]
 [8.5 8.5]]


### Πράξεις μεταξύ πινάκων

Οι πίνακες ``NumPy`` μπορούν να χρησιμοποιηθούν σε μαθηματικές πράξεις και συμπεριφέρονται όπως θα περίμενε κανείς με στοιχειώδεις γνώσεις γραμμικής άλγεβρας.

Οι μαθηματικές πράξεις μεταξύ πινάκων ``Numpy`` πραγματοποιούνται **πάντα** στοιχείο-στοιχείο (elementwise). Αυτή η έννοια της "διανυσματικοποίησης", που δεν υπάρχει εγγενώς στην Python, επιτρέπει ταχύτατους υπολογισμούς.

Σχεδόν *ποτέ* δεν είναι καλή επιλογή να δουλεύετε με πίνακες χρησιμοποιώντας βρόγχους επανάληψης για να επιτελέσετε κάποια πράξη καθώς με αυτόν τον τρόπο χάνετε την ταχύτητα που σας προσφέρει η διανυσματικοποίηση.


Το παρακάτω παράδειγμα του πολλαπλασιασμού ενός βαθμωτού μεγέθους με έναν πίνακα και μία λίστα επιδεικνύει τις δυνατότητες της διανυσματικοποίησης.

In [15]:
# A common list
L = [1,2,3]

# The array version of L
A = np.array(L)

# Multiplication of a scalar with an array
print(2*A)

# Multiplication of a scalar with a list
print(2*L)

# In order to do the same with the list
# we need to use a for-loop. This is very
# inneficient compared to the vectorization
# provided by numpy arrays
for idx, val in enumerate(L):
    L[idx] = 2*val
print(L)

[2 4 6]
[1, 2, 3, 1, 2, 3]
[2, 4, 6]


In [16]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)   # element-wise addition
print(x * y)   # element-wise multiplication
print(x + 2 * y)  # more complex manipulation
print(x**y)

[5 7 9]
[ 4 10 18]
[ 9 12 15]
[  1  32 729]


Η διανυσματικοποίηση προσφέρει την χρήση συναρτήσεων υψηλών επιδόσεων.

In [17]:
# Create the x-space
x = np.linspace(0.0, 2.0 * np.pi, 50)

# Find the y-value for each point in the x-space
y = np.sin(x)

# Find the sum of x-space
z = np.sum(x)

print(y)
print(z)

[ 0.00000000e+00  1.27877162e-01  2.53654584e-01  3.75267005e-01
  4.90717552e-01  5.98110530e-01  6.95682551e-01  7.81831482e-01
  8.55142763e-01  9.14412623e-01  9.58667853e-01  9.87181783e-01
  9.99486216e-01  9.95379113e-01  9.74927912e-01  9.38468422e-01
  8.86599306e-01  8.20172255e-01  7.40277997e-01  6.48228395e-01
  5.45534901e-01  4.33883739e-01  3.15108218e-01  1.91158629e-01
  6.40702200e-02 -6.40702200e-02 -1.91158629e-01 -3.15108218e-01
 -4.33883739e-01 -5.45534901e-01 -6.48228395e-01 -7.40277997e-01
 -8.20172255e-01 -8.86599306e-01 -9.38468422e-01 -9.74927912e-01
 -9.95379113e-01 -9.99486216e-01 -9.87181783e-01 -9.58667853e-01
 -9.14412623e-01 -8.55142763e-01 -7.81831482e-01 -6.95682551e-01
 -5.98110530e-01 -4.90717552e-01 -3.75267005e-01 -2.53654584e-01
 -1.27877162e-01 -2.44929360e-16]
157.07963267948966


### Δείκτες πινάκων - τεμαχισμός πινάκων (indexing - slicing)

* Για τους μονοδιάστατους πίνακες η προσπέλαση καθώς και ο τεμαχισμός είναι παρόμοιος με αυτόν που συναντήσαμε στις λίστες της Python.

In [13]:
# Slicing a 1D array
a = np.arange(0, 11, 1)

print(a)
print(a[5])    # access element with index 5
print(a[2:6])  # access index 2 (inclusive) up index six (exclusive)
print(a[2:6:2]) # access every other element starting from the second
print(a[2:])   # access all elements starting from index 2
print(a[:-1])  # access all elements except the last

[ 0  1  2  3  4  5  6  7  8  9 10]
5
[2 3 4 5]
[2 4]
[ 2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]


* Για τους πολυδιάστατους πίνακες ισχύουν οι ίδιοι κανόνες όπως και στη μία διάσταση. Οι δύο διαστάσεις διαχειρίζονται *ανεξάρτητα η μία από την άλλη* και διαχωρίζονται με ένα κόμμα. Ο πρώτος δείκτης αναφέρεται στις γραμμές ενώ ο δεύτερος στις στήλες: ``array[row, col]``

In [24]:
# Slicing a 2D array
a = np.array([[23,14,5], [12, 6, 52], [9, 4, 15]])

print(a)
print(a[1,2])                    # access element of second row, third column
                                 # first index = row, second index = column
    
print(a[1:3,2])                  # access elements in the second and third row and
                                 # the third column  
    
print(a[:,2])                    # access elements of third column  

print(a[2,:])                    # access elements of third row

print(a[0:-1, 1:-1])              # access 2D-subarray

a[1,:] = 100                     # slicing on the left-side of an assignment                
                                 # substitute subarray

print(a)

[[23 14  5]
 [12  6 52]
 [ 9  4 15]]
52
[52 15]
[ 5 52 15]
[ 9  4 15]
[[14]
 [ 6]]
[[ 23  14   5]
 [100 100 100]
 [  9   4  15]]


### Χρήσιμες συναρτήσεις πινάκων

### Masking

### Broadcasting

### Εισαγωγή δεδομένων από αρχείο